"use client";

import Link from "next/link";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatPrice } from "@/lib/data";

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  if (!items.length) return <div className="container-page py-24 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-[#f8eadc] text-orange"><ShoppingBag/></div><h1 className="display mt-5 text-5xl">Your cart is empty</h1><p className="mt-3 text-stone-600">The pet pantry is only a click away.</p><Link href="/shop" className="mt-7 inline-flex min-h-12 items-center rounded-xl bg-orange px-6 font-black text-white">Browse products</Link></div>;
  return <div className="container-page py-12 md:py-16"><h1 className="display text-5xl md:text-6xl">Your cart</h1><div className="mt-9 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="grid gap-3">{items.map(({ product, quantity }) => <article key={product.id} className="grid grid-cols-[76px_1fr] gap-4 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[90px_1fr_auto]"><div className="grid min-h-20 place-items-center rounded-xl bg-[#f7eee1]"><div className="product-bag !h-[70px] !w-[44px] !rounded-lg" style={{ "--bag": product.color } as React.CSSProperties}/></div><div><Link href={`/product/${product.slug}`} className="font-black hover:text-orange">{product.name}</Link><p className="mt-1 text-sm text-stone-500">{product.weight}</p><p className="mt-2 font-black">{formatPrice(product.price * quantity)}</p></div><div className="col-span-2 flex items-center justify-between sm:col-span-1 sm:flex-col sm:items-end"><div className="flex items-center rounded-xl border border-line"><button className="grid min-h-11 min-w-11 place-items-center" onClick={() => updateQuantity(product.id, quantity - 1)} aria-label="Decrease quantity"><Minus size={16}/></button><span className="min-w-8 text-center font-bold">{quantity}</span><button className="grid min-h-11 min-w-11 place-items-center" onClick={() => updateQuantity(product.id, quantity + 1)} aria-label="Increase quantity"><Plus size={16}/></button></div><button onClick={() => removeItem(product.id)} className="flex min-h-11 items-center gap-2 text-sm font-bold text-red-700 hover:underline"><Trash2 size={16}/>Remove</button></div></article>)}</div><aside className="h-fit rounded-[24px] bg-ink p-6 text-white lg:sticky lg:top-32"><h2 className="text-xl font-black">Order summary</h2><div className="mt-6 flex justify-between border-b border-white/15 pb-5 text-sm"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p className="mt-4 text-sm leading-6 text-[#d7c6b8]">Delivery charge will be confirmed based on your address. Payment is Cash on Delivery only.</p><Link href="/checkout" className="mt-6 flex min-h-12 w-full items-center justify-center rounded-xl bg-amber px-5 font-black text-ink hover:bg-[#ffc533]">Continue to order</Link><Link href="/shop" className="mt-2 flex min-h-11 items-center justify-center text-sm font-bold text-[#d7c6b8] hover:text-white">Keep shopping</Link></aside></div></div>;
}
