import { Category, Product } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Cat Food",
    slug: "cat-food",
    description: "Dry food, wet gravy pouches, mousse and complete daily nutrition for adult cats & kittens.",
    symbol: "🐱",
    image: "/images/categories/adult-food.png",
    itemCount: 12,
  },
  {
    id: "2",
    name: "Cat Toys",
    slug: "cat-toys",
    description: "Interactive door hangers, feather wands, rolling balls and scratching tunnels.",
    symbol: "🎾",
    image: "/images/categories/cat-litter-accessories.png",
    itemCount: 8,
  },
  {
    id: "3",
    name: "Cat Litter",
    slug: "cat-litter",
    description: "Tofu clumping litter, bentonite clay, deodorizing crystals and cat litter trays.",
    symbol: "🧺",
    image: "/images/categories/clumping-cat-litter.jpg",
    itemCount: 6,
  },
  {
    id: "4",
    name: "Cat Care & Health",
    slug: "cat-care-health",
    description: "Flea control, deworming supplements, grooming gloves and health essentials.",
    symbol: "🩺",
    image: "/images/categories/care.jpg",
    itemCount: 10,
  },
  {
    id: "5",
    name: "Clothing, Beds & Carrier",
    slug: "clothing-beds-carrier",
    description: "Cozy pet beds, travel capsule backpacks, pet clothing and carriers.",
    symbol: "👕",
    image: "/images/categories/feeding.png",
    itemCount: 6,
  },
  {
    id: "6",
    name: "Cat Accessories",
    slug: "cat-accessories",
    description: "Collars, harnesses, water fountains, food bowls and feeding accessories.",
    symbol: "🎀",
    image: "/images/categories/collar.png",
    itemCount: 14,
  },
  {
    id: "7",
    name: "Dog Health & Accessories",
    slug: "dog-health-accessories",
    description: "Dog leashes, chew toys, grooming brushes, dental care and tick sprays.",
    symbol: "🦴",
    image: "/images/categories/care.jpg",
    itemCount: 8,
  },
  {
    id: "8",
    name: "Dog Food",
    slug: "dog-food",
    description: "High-protein dry kibble, puppy starters and meaty canned food for dogs.",
    symbol: "🐶",
    image: "/images/categories/adult-food.png",
    itemCount: 10,
  },
  {
    id: "9",
    name: "Rabbit Food & Accessories",
    slug: "rabbit-food-accessories",
    description: "Hay, nutritious pellets, water feeders and cage bedding for small pets.",
    symbol: "🐇",
    image: "/images/categories/feeding.png",
    itemCount: 4,
  },
  {
    id: "10",
    name: "Bird Food & Accessories",
    slug: "bird-food-accessories",
    description: "Seed mixtures, cuttlebone supplements, cages and bird perches.",
    symbol: "🦜",
    image: "/images/categories/feeding.png",
    itemCount: 4,
  },
];

// Featured Categories: 6 items
export const featuredCategoryBoxes = [
  { name: "ADULT FOOD", slug: "cat-food", image: "/images/categories/adult-food.png" },
  { name: "KITTEN FOOD", slug: "cat-food", image: "/images/categories/kitten-food.png" },
  { name: "COLLAR", slug: "cat-accessories", image: "/images/categories/collar.png" },
  { name: "CLUMPING CAT LITTER", slug: "cat-litter", image: "/images/categories/clumping-cat-litter.jpg" },
  { name: "CAT LITTER ACCESSORIES", slug: "cat-litter", image: "/images/categories/cat-litter-accessories.png" },
  { name: "HARNESS", slug: "cat-accessories", image: "/images/categories/harness.png" },
];

export const subcategoryChips = [
  { name: "HARNESS", href: "/category/cat-accessories" },
  { name: "CAT TICK & FLEA...", href: "/category/cat-care-health" },
  { name: "DEWORMING TABLET", href: "/category/cat-care-health" },
  { name: "CAT POUCHES", href: "/category/cat-food" },
  { name: "SUNGLASS", href: "/category/cat-accessories" },
];

export const products: Product[] = [
  {
    id: "1017832",
    barcode: "1017832",
    name: "Aodemei Pet Comb Set",
    slug: "aodemei-pet-comb-set",
    categorySlug: "cat-accessories",
    categoryName: "Pet Accessories",
    brand: "AODEMEI",
    price: 585,
    stock: 10,
    weight: "1 pack",
    description: "A practical grooming comb set for regular dog and cat coat care. The different grooming surfaces help lift loose hair, work through small tangles and keep the coat neat between professional grooming sessions.",
    imageUrl: "/images/products/catalog/aodemei-pet-comb-set.jpg",
    featured: true,
  },
  {
    id: "1018520",
    barcode: "1018520",
    name: "Areion Vet Feli-D Oral Suspension",
    slug: "areion-vet-feli-d-oral-suspension-15ml",
    categorySlug: "cat-care-health",
    categoryName: "Cat Care & Health",
    brand: "AREION VET",
    price: 310,
    stock: 10,
    weight: "15 ml",
    description: "A 15 ml oral deworming suspension formulated for kittens, containing pyrantel pamoate and febantel. It is intended for the treatment and control of common intestinal worms. Veterinary medicine: use only under veterinary direction and follow the supplied dosage instructions.",
    imageUrl: "/images/products/catalog/areion-vet-feli-d.png",
    featured: true,
  },
  {
    id: "1014865",
    barcode: "1014865",
    name: "Bayer Drontal Plus",
    slug: "bayer-drontal-plus-1-tablet",
    categorySlug: "dog-food",
    categoryName: "Dog Food",
    brand: "BAYER",
    price: 150,
    stock: 10,
    weight: "1 tablet",
    description: "A single Drontal Plus tablet for dogs, formulated with praziquantel, pyrantel embonate and febantel for broad-spectrum intestinal worm control. Veterinary medicine: the correct dose depends on the dog’s weight, so use only under veterinary direction and follow the original pack instructions.",
    imageUrl: "/images/products/catalog/bayer-drontal-plus.jpg",
    featured: true,
  },
  {
    id: "8852021705691",
    barcode: "8852021705691",
    name: "Bellotta Adult Mackerel Wet Cat Food",
    slug: "bellotta-adult-mackerel-wet-cat-food-85g",
    categorySlug: "cat-food",
    categoryName: "Cat Food",
    brand: "BELLOTTA",
    price: 85,
    stock: 10,
    weight: "85 g pouch",
    description: "An 85 g wet food pouch made with mackerel for adult cats. The recipe includes taurine, vitamins and minerals, with no added preservatives, and the single-serve pouch makes everyday feeding simple.",
    imageUrl: "/images/products/catalog/bellotta-mackerel-85g.jpg",
    featured: true,
    bestSeller: true,
  },
  {
    id: "1016197",
    barcode: "1016197",
    name: "Haisenpet Apple Bentonite Cat Litter",
    slug: "haisenpet-apple-bentonite-cat-litter-10l",
    categorySlug: "cat-litter",
    categoryName: "Cat Litter",
    brand: "HAISENPET",
    price: 630,
    stock: 10,
    weight: "10 L pack",
    description: "Apple-scented bentonite cat litter made for fast clumping, strong absorption and everyday odour control. The low-dust granules form firm clumps for easier scooping and help keep the litter area fresher between full changes.",
    imageUrl: "/images/products/catalog/haisenpet-apple-10l.png",
    bestSeller: true,
  },
  {
    id: "6970117121421",
    barcode: "6970117121421",
    name: "Bioline Pet Lint Roller",
    slug: "bioline-pet-lint-roller-60-sheets",
    categorySlug: "cat-accessories",
    categoryName: "Pet Accessories",
    brand: "BIOLINE",
    price: 330,
    stock: 10,
    weight: "1 piece / 60 sheets",
    description: "A refillable pet lint roller with 60 adhesive sheets. It quickly lifts loose cat and dog hair, lint and dust from clothing, sofas, bedding and car upholstery without needing water or cleaning spray.",
    imageUrl: "/images/products/catalog/bioline-pet-roller.jpg",
  },
  {
    id: "1015528",
    barcode: "1015528",
    name: "Bioline Calming Shampoo",
    slug: "bioline-calming-shampoo-250ml",
    categorySlug: "cat-care-health",
    categoryName: "Cat Care & Health",
    brand: "BIOLINE",
    price: 730,
    stock: 10,
    weight: "250 ml bottle",
    description: "A 250 ml calming shampoo for dogs and cats, made with chamomile and lavender extracts. It gently cleans the coat while leaving it fresh, and is suited to routine baths for pets that may feel unsettled during grooming.",
    imageUrl: "/images/products/catalog/bioline-calming-shampoo.png",
  },
  {
    id: "1017834",
    barcode: "1017834",
    name: "Bioline Glossy Coat Shampoo",
    slug: "bioline-glossy-coat-shampoo-250ml",
    categorySlug: "cat-care-health",
    categoryName: "Cat Care & Health",
    brand: "BIOLINE",
    price: 730,
    stock: 10,
    weight: "250 ml bottle",
    description: "A 250 ml shampoo for cats and dogs designed to clean oily and greasy coats. It removes everyday dirt and excess oil while conditioning the fur and leaving the coat clean, fresh and glossy.",
    imageUrl: "/images/products/catalog/bioline-glossy-coat.jpg",
  },
  {
    id: "6970117127164",
    barcode: "6970117127164",
    name: "Bioline Norwegian Salmon Oil",
    slug: "bioline-norwegian-salmon-oil-250ml",
    categorySlug: "dog-health-accessories",
    categoryName: "Dog & Cat Oil",
    brand: "BIOLINE",
    price: 1190,
    stock: 10,
    weight: "250 ml bottle",
    description: "Norwegian salmon oil supplement for dogs and cats, naturally rich in omega-3 and omega-6 fatty acids. It can be mixed with regular food to support energy, skin and coat condition, and normal joint mobility. Follow the feeding directions on the bottle.",
    imageUrl: "/images/products/catalog/bioline-salmon-oil.jpg",
    bestSeller: true,
  },
  {
    id: "1016958",
    barcode: "1016958",
    name: "Catnip Ball Stand Toy",
    slug: "catnip-ball-stand-toy",
    categorySlug: "cat-toys",
    categoryName: "Pet Toy",
    brand: "CHINA",
    price: 675,
    stock: 10,
    weight: "1 piece",
    description: "A freestanding rotating catnip ball made for batting, rubbing and self-directed play. The raised stand keeps the ball accessible from different angles and gives indoor cats a simple way to stay curious and active.",
    imageUrl: "/images/products/catalog/catnip-ball-stand.jpg",
  },
  {
    id: "1016966",
    barcode: "1016966",
    name: "Natural Flax Rope Cat Toy",
    slug: "natural-flax-rope-cat-toy",
    categorySlug: "cat-toys",
    categoryName: "Pet Toy",
    brand: "CHINA",
    price: 375,
    stock: 10,
    weight: "1 piece",
    description: "A lightweight cat toy wrapped in textured natural flax-style fibre. It is easy for cats to bat, chase, grab and chew during supervised play, helping redirect playful scratching and biting away from household items.",
    imageUrl: "/images/products/catalog/flax-rope-cat-toy.png",
  },
  {
    id: "8859601044720",
    barcode: "8859601044720",
    name: "Pramy Goat Milk with Colostrum & Algae Oil",
    slug: "pramy-goat-milk-colostrum-algae-oil-60g",
    categorySlug: "cat-food",
    categoryName: "Dog & Cat Food",
    brand: "PRAMY",
    price: 120,
    stock: 10,
    weight: "60 g pouch",
    description: "Premium sterilized goat milk with colostrum and DHA/EPA from algae oil for cats and dogs. The easy-to-digest, grain-free formula provides calcium, phosphorus and essential amino acids while supporting normal brain development, vision, immunity and digestion.",
    imageUrl: "/images/products/catalog/pramy-goat-milk-algae-oil.jpg",
  },
  {
    id: "8859601044737",
    barcode: "8859601044737",
    name: "Pramy Goat Milk with Colostrum & Postbiotic",
    slug: "pramy-goat-milk-colostrum-postbiotic-60g",
    categorySlug: "cat-food",
    categoryName: "Dog & Cat Food",
    brand: "PRAMY",
    price: 120,
    stock: 10,
    weight: "60 g pouch",
    description: "Premium sterilized goat milk with colostrum and added postbiotic for cats and dogs. The grain-free, easy-to-digest formula provides calcium, phosphorus and essential amino acids, with postbiotic support for normal immunity and digestive health.",
    imageUrl: "/images/products/catalog/pramy-goat-milk-postbiotic.jpg",
  },
];

export const formatPrice = (value: number) => {
  if (!value || value <= 0) return "Price on Call";
  return `BDT ${value.toLocaleString("en-BD")}`;
};

export const findProduct = (slug: string) => products.find((product) => product.slug === slug);
