import { Category, Product } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Cat Food",
    slug: "cat-food",
    description: "Dry food, wet gravy pouches, mousse and complete daily nutrition for adult cats & kittens.",
    symbol: "🐱",
    image: "/images/categories/adult-food.png",
    itemCount: 12,
  },
  {
    id: "2",
    name: "Cat Toys",
    slug: "cat-toys",
    description: "Interactive door hangers, feather wands, rolling balls and scratching tunnels.",
    symbol: "🎾",
    image: "/images/categories/cat-litter-accessories.png",
    itemCount: 8,
  },
  {
    id: "3",
    name: "Cat Litter",
    slug: "cat-litter",
    description: "Tofu clumping litter, bentonite clay, deodorizing crystals and cat litter trays.",
    symbol: "🧺",
    image: "/images/categories/clumping-cat-litter.jpg",
    itemCount: 6,
  },
  {
    id: "4",
    name: "Cat Care & Health",
    slug: "cat-care-health",
    description: "Flea control, deworming supplements, grooming gloves and health essentials.",
    symbol: "🩺",
    image: "/images/categories/care.jpg",
    itemCount: 10,
  },
  {
    id: "5",
    name: "Clothing, Beds & Carrier",
    slug: "clothing-beds-carrier",
    description: "Cozy pet beds, travel capsule backpacks, pet clothing and carriers.",
    symbol: "👕",
    image: "/images/categories/feeding.png",
    itemCount: 6,
  },
  {
    id: "6",
    name: "Cat Accessories",
    slug: "cat-accessories",
    description: "Collars, harnesses, water fountains, food bowls and feeding accessories.",
    symbol: "🎀",
    image: "/images/categories/collar.png",
    itemCount: 14,
  },
  {
    id: "7",
    name: "Dog Health & Accessories",
    slug: "dog-health-accessories",
    description: "Dog leashes, chew toys, grooming brushes, dental care and tick sprays.",
    symbol: "🦴",
    image: "/images/categories/care.jpg",
    itemCount: 8,
  },
  {
    id: "8",
    name: "Dog Food",
    slug: "dog-food",
    description: "High-protein dry kibble, puppy starters and meaty canned food for dogs.",
    symbol: "🐶",
    image: "/images/categories/adult-food.png",
    itemCount: 10,
  },
  {
    id: "9",
    name: "Rabbit Food & Accessories",
    slug: "rabbit-food-accessories",
    description: "Hay, nutritious pellets, water feeders and cage bedding for small pets.",
    symbol: "🐇",
    image: "/images/categories/feeding.png",
    itemCount: 4,
  },
  {
    id: "10",
    name: "Bird Food & Accessories",
    slug: "bird-food-accessories",
    description: "Seed mixtures, cuttlebone supplements, cages and bird perches.",
    symbol: "🦜",
    image: "/images/categories/feeding.png",
    itemCount: 4,
  },
];

// Featured Categories: 6 items
export const featuredCategoryBoxes = [
  { name: "ADULT FOOD", slug: "cat-food", image: "/images/categories/adult-food.png" },
  { name: "KITTEN FOOD", slug: "cat-food", image: "/images/categories/kitten-food.png" },
  { name: "COLLAR", slug: "cat-accessories", image: "/images/categories/collar.png" },
  { name: "CLUMPING CAT LITTER", slug: "cat-litter", image: "/images/categories/clumping-cat-litter.jpg" },
  { name: "CAT LITTER ACCESSORIES", slug: "cat-litter", image: "/images/categories/cat-litter-accessories.png" },
  { name: "HARNESS", slug: "cat-accessories", image: "/images/categories/harness.png" },
];

export const subcategoryChips = [
  { name: "HARNESS", href: "/category/cat-accessories" },
  { name: "CAT TICK & FLEA...", href: "/category/cat-care-health" },
  { name: "DEWORMING TABLET", href: "/category/cat-care-health" },
  { name: "CAT POUCHES", href: "/category/cat-food" },
  { name: "SUNGLASS", href: "/category/cat-accessories" },
];

// CLEAN UNBRANDED PLACEHOLDER PRODUCTS (NO PRICES OR FAKE NAMES)
export const products: Product[] = [
  {
    id: "ph1",
    name: "Product Item #01",
    slug: "product-item-01",
    categorySlug: "cat-food",
    categoryName: "Cat Food",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph2",
    name: "Product Item #02",
    slug: "product-item-02",
    categorySlug: "cat-food",
    categoryName: "Cat Food",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph3",
    name: "Product Item #03",
    slug: "product-item-03",
    categorySlug: "dog-food",
    categoryName: "Dog Food",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph4",
    name: "Product Item #04",
    slug: "product-item-04",
    categorySlug: "dog-food",
    categoryName: "Dog Food",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph5",
    name: "Product Item #05",
    slug: "product-item-05",
    categorySlug: "cat-litter",
    categoryName: "Cat Litter",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph6",
    name: "Product Item #06",
    slug: "product-item-06",
    categorySlug: "cat-toys",
    categoryName: "Cat Toys",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph7",
    name: "Product Item #07",
    slug: "product-item-07",
    categorySlug: "cat-care-health",
    categoryName: "Cat Care & Health",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph8",
    name: "Product Item #08",
    slug: "product-item-08",
    categorySlug: "clothing-beds-carrier",
    categoryName: "Clothing, Beds & Carrier",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph9",
    name: "Product Item #09",
    slug: "product-item-09",
    categorySlug: "cat-accessories",
    categoryName: "Cat Accessories",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph10",
    name: "Product Item #10",
    slug: "product-item-09",
    categorySlug: "dog-health-accessories",
    categoryName: "Dog Health & Accessories",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph11",
    name: "Product Item #11",
    slug: "product-item-11",
    categorySlug: "rabbit-food-accessories",
    categoryName: "Rabbit Food & Accessories",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
  {
    id: "ph12",
    name: "Product Item #12",
    slug: "product-item-12",
    categorySlug: "bird-food-accessories",
    categoryName: "Bird Food & Accessories",
    brand: "DHALI'S",
    price: 0,
    stock: 20,
    weight: "In Stock Soon",
    description: "Product details, photos, and pricing will be uploaded shortly by store administration.",
    color: "#F9FAFB",
    featured: true,
  },
];

export const formatPrice = (value: number) => {
  if (!value || value <= 0) return "Price on Call";
  return `৳${value.toLocaleString("en-BD")}`;
};

export const findProduct = (slug: string) => products.find((product) => product.slug === slug);
