"use client";

import Image from "next/image";
import { useActionState, useEffect, useRef, useState } from "react";
import { ImagePlus, LoaderCircle, UploadCloud, X } from "lucide-react";
import { createProduct, type ProductActionState } from "@/app/admin/actions";

type Category = { id: string; name: string };
const initialState: ProductActionState = {};

export function ProductUploadForm({ categories }: { categories: Category[] }) {
  const [state, action, pending] = useActionState(createProduct, initialState); const [preview, setPreview] = useState(""); const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.success) { formRef.current?.reset(); setPreview(""); } }, [state.success]);
  return <form ref={formRef} action={action} className="grid gap-6 rounded-2xl bg-white p-5 shadow-[0_10px_30px_rgba(43,23,20,.06)] md:p-7">
    <div><h2 className="font-display text-3xl font-bold">Upload a product</h2><p className="mt-1 text-sm text-muted">Add the details customers need. The product publishes after a successful save.</p></div>
    <div className="grid gap-6 lg:grid-cols-[240px_1fr]"><div><label className="group relative grid aspect-square cursor-pointer place-items-center overflow-hidden rounded-2xl border border-dashed border-clay bg-mist text-center hover:border-papaya"><input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/avif" className="sr-only" onChange={(event)=>{const file=event.target.files?.[0];if(file){if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));}}}/>{preview?<Image src={preview} alt="Selected product preview" fill className="object-contain p-3" unoptimized/>:<span className="px-5"><ImagePlus className="mx-auto text-papaya" size={32}/><strong className="mt-3 block">Choose product image</strong><small className="mt-1 block text-muted">JPG, PNG, WebP or AVIF, max 5 MB</small></span>}</label>{preview&&<button type="button" onClick={()=>setPreview("")} className="mt-2 flex min-h-11 items-center gap-2 text-sm font-bold text-red-700"><X size={16}/>Remove preview</button>}</div>
      <div className="grid gap-4"><label className="field">Product name<input name="name" required minLength={2} placeholder="Ocean Fish Adult Cat Food"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="field">Category<select name="categoryId" required defaultValue=""><option value="" disabled>Select category</option>{categories.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field">Weight or size<input name="weight" required placeholder="1.2 kg"/></label></div><div className="grid gap-4 sm:grid-cols-3"><label className="field">Price (BDT)<input name="price" required min="1" type="number" inputMode="numeric"/></label><label className="field">Old price (BDT)<input name="compareAt" min="0" type="number" inputMode="numeric"/></label><label className="field">Stock<input name="stock" required min="0" type="number" inputMode="numeric"/></label></div><label className="field">Short description<textarea name="description" required minLength={10} rows={4} placeholder="What makes this product useful?"/></label><label className="field">Badge <span className="font-normal text-muted">optional</span><input name="badge" maxLength={30} placeholder="New or Save BDT 100"/></label><div className="flex flex-wrap gap-5"><label className="flex min-h-11 items-center gap-2 font-bold"><input name="featured" type="checkbox" className="h-5 w-5 accent-papaya"/>Featured</label><label className="flex min-h-11 items-center gap-2 font-bold"><input name="bestSeller" type="checkbox" className="h-5 w-5 accent-papaya"/>Best seller</label></div></div></div>
    {state.error&&<p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-800">{state.error}</p>}{state.success&&<p role="status" className="rounded-xl bg-mint px-4 py-3 text-sm font-bold text-sage">{state.success}</p>}<button disabled={pending||!categories.length} className="inline-flex min-h-12 w-fit items-center gap-2 rounded-xl bg-papaya px-6 font-black text-white hover:bg-papaya-dark disabled:cursor-not-allowed disabled:opacity-60">{pending?<LoaderCircle className="animate-spin" size={18}/>:<UploadCloud size={19}/>} {pending?"Uploading product":"Upload product"}</button>
  </form>;
}
